name: desktop_context_menu_platform_interface
description: A common platform interface for desktop_context_menu.
version: 0.1.1
homepage: https://github.com/rows/desktop_context_menu/tree/main/desktop_context_menu_platform_interface

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  rows_lint: 0.1.1
  flutter_test:
    sdk: flutter