name: desktop_context_menu
description: A plugin that opens a context menu on the cursor position.
version: 0.1.0
repository: https://github.com/rows/desktop_context_menu/tree/main/desktop_context_menu
homepage: https://github.com/rows/desktop_context_menu/tree/main/desktop_context_menu
issue_tracker: https://github.com/rows/desktop_context_menu/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  desktop_context_menu_platform_interface: ^0.1.0
  desktop_context_menu_windows: ^0.1.0
  desktop_context_menu_macos: ^0.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  rows_lint: 0.1.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        default_package: desktop_context_menu_windows
      macos:
        default_package: desktop_context_menu_macos
