name: desktop_context_menu_example
description: Demonstrates how to use the desktop_context_menu plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  desktop_context_menu:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  rows_lint: 0.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true