name: pull-request

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install flutter
      uses: subosito/flutter-action@master
      with:
        channel: 'stable'

    - name: Get dependencies
      run: sh/scripts/install.sh

    - name: Run formatter
      run: sh scripts/format.sh

    - name: Run analyzer
      run: sh scripts/analyze.sh

    - name: Run unit tests
      run: sh scripts/tests.sh