name: pull-request

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install flutter
      uses: subosito/flutter-action@master
      with:
        channel: 'stable'

    - name: Activate melos
      run: bluefireteam/melos-action@v1

    - name: Run formatter
      run: melos run format

    - name: Run analyzer
      run: melos run analyze

    - name: Run unit tests
      run: melos run test --no-select